before_script:
  variables:
    CI_DEBUG_TRACE: "true"

# Run sequentially and stop if anyone stage fails
stages:
  - python2.7
  - python3.6
  - flake8

python2.7:
  stage: python2.7
  script:
    - source test_job 2.7

python3.6:
  stage: python3.6
  script:
    - source test_job 3.6

flake8:
  stage: flake8
  script:
    - flake8
