variables:
  CONTAINER_URL: "code.ornl.gov:4567/sns-hfir-scse/sans/sans-backend/$CI_COMMIT_REF_NAME"

stages:
  - dockerbuild
  - docker-test

dockerbuild:
  stage: dockerbuild
  before_script:
    - docker system prune -f
    - docker image prune -af
  script:
    - docker build -t $CONTAINER_URL .
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CONTAINER_URL
    - sed -i "s|CONTAINER_URL|$CONTAINER_URL|" scripts/sans-backend-run.sh
  tags:
    - scse-mantid-builder
  artifacts:
    paths:
    - scripts/sans-backend-run.sh
  only:
    - c1u-dockerfile

docker-update-test:
  stage: docker-test
  dependencies: 
    - dockerbuild
  before_script:
    - docker system prune -f
    - docker image prune -af
  script:
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - sh scripts/sans-backend-run.sh -u -- test.py
  tags:
    - scse-mantid-builder
  only:
    - c1u-dockerfile

docker-no-update-test:
  stage: docker-test
  dependencies: 
    - dockerbuild
  before_script:
    - docker system prune -f
    - docker image prune -af
  script:
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - sh scripts/sans-backend-run.sh -- test.py
  tags:
    - scse-mantid-builder
  only:
    - c1u-dockerfile
