job1:
  script:
    - module load mantid/ORNL_SANS
    - which MantidPlot
    - virtualenv -p $(which python2) testenv &> /tmp/gitlab-ci.log
    - source testenv/bin/activate >> /tmp/gitlab-ci.log
    - pip install -u requirements.txt >> /tmp/gitlab-ci.log
    - pwd >> /tmp/gitlab-ci.log
