job1:
  script:
    - module load mantid/ORNL_SANS
    - which MantidPlot
    - virtualenv -p $(which python2) testenv &> /tmp/gitlab-ci.log
    - source testenv/bin/activate >> /tmp/gitlab-ci.log 2>&1
    - pip install -r requirements.txt >> /tmp/gitlab-ci.log 2>&1
    - pip install -r requirements_dev.txt >> /tmp/gitlab-ci.log 2>&1
    - pwd >> /tmp/gitlab-ci.log 2>&1

