variables:
  CONTAINER_URL: "code.ornl.gov:4567/sns-hfir-scse/sans/sans-backend/$CI_COMMIT_REF_NAME"
  TEST_SCOPE: "unit"

stages:
  - flake8
  - dockerbuild
  - docker-test
  - code-test
  - script-host

flake8:
  stage: flake8
  allow_failure: true
  before_script:
    - sudo cp fix_runner_perms.sh /etc/cron.hourly/fix_runner_perms.sh
    - sudo chmod +x /etc/cron.hourly/fix_runner_perms.sh
  script:
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker run -v $PWD:/opt/sans-backend -t code.ornl.gov:4567/sns-hfir-scse/docker-containers/mantid-framework-nightly/master bash -c "flake8 /opt/sans-backend"
    - sudo chown -R gitlab-runner .
  tags:
    - scse-mantid-builder

dockerbuild:
  stage: dockerbuild
  before_script:
    - docker system prune -f
    - docker image prune -af
    - sudo cp fix_runner_perms.sh /etc/cron.hourly/fix_runner_perms.sh
    - sudo chmod +x /etc/cron.hourly/fix_runner_perms.sh
  script:
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull code.ornl.gov:4567/sns-hfir-scse/docker-containers/mantid-framework-nightly/master
    - docker build -t $CONTAINER_URL .
    - docker push $CONTAINER_URL
    - sed -i "s|CONTAINER_URL|$CONTAINER_URL|" scripts/sans-backend-run.sh
    - sudo chown -R gitlab-runner .
  tags:
    - scse-mantid-builder
  artifacts:
    paths:
    - scripts/sans-backend-run.sh

docker-update-test:
  stage: docker-test
  dependencies: 
    - dockerbuild
  before_script:
    - sudo cp fix_runner_perms.sh /etc/cron.hourly/fix_runner_perms.sh
    - sudo chmod +x /etc/cron.hourly/fix_runner_perms.sh
  script:
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_URL
    - sh -x scripts/sans-backend-run.sh -u scripts/docker-test.py
    - sudo chown -R gitlab-runner .
  tags:
    - scse-mantid-builder

docker-no-update-test:
  stage: docker-test
  dependencies: 
    - dockerbuild
  before_script:
    - sudo cp fix_runner_perms.sh /etc/cron.hourly/fix_runner_perms.sh
    - sudo chmod +x /etc/cron.hourly/fix_runner_perms.sh
  script:
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_URL
    - sh -x scripts/sans-backend-run.sh scripts/docker-test.py
    - sudo chown -R gitlab-runner .
  tags:
    - scse-mantid-builder

code-unit-test:
  stage: code-test
  dependencies: 
    - dockerbuild
  allow_failure: true
  before_script:
    - sudo cp fix_runner_perms.sh /etc/cron.hourly/fix_runner_perms.sh
    - sudo chmod +x /etc/cron.hourly/fix_runner_perms.sh
  script:
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_URL
    - docker run -v $PWD:/opt/sans-backend -t $CONTAINER_URL bash -c "bash /opt/sans-backend/test_job.sh ${TEST_SCOPE}"
    - sudo chown -R gitlab-runner .
  tags:
    - scse-mantid-builder

code-integration-test:
  stage: code-test
  dependencies: 
    - dockerbuild
  allow_failure: true
  before_script:
    - sudo cp fix_runner_perms.sh /etc/cron.hourly/fix_runner_perms.sh
    - sudo chmod +x /etc/cron.hourly/fix_runner_perms.sh
  script:
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_URL
    - docker run -v $PWD:/opt/sans-backend -t $CONTAINER_URL bash -c "bash /opt/sans-backend/test_job.sh integration"
    - sudo chown -R gitlab-runner .
  tags:
    - scse-mantid-builder

script-host:
  stage: script-host
  dependencies: 
    - dockerbuild
  before_script:
    - sudo yum install -y httpd
    - sudo rm -f /etc/httpd/conf.d/welcome.conf
    - sudo systemctl restart httpd
    - sudo cp fix_runner_perms.sh /etc/cron.hourly/fix_runner_perms.sh
    - sudo chmod +x /etc/cron.hourly/fix_runner_perms.sh
  script:
    - sudo mkdir -p /var/www/html/sans-backend/$CI_COMMIT_REF_NAME
    - sudo ls -la /var/www/html/
    - sudo cp -f scripts/sans-backend-run.sh /var/www/html/sans-backend/$CI_COMMIT_REF_NAME/
    - sudo chmod -R 755 /var/www/html/
    - curl http://localhost/sans-backend/$CI_COMMIT_REF_NAME/sans-backend-run.sh
    - sudo chown -R gitlab-runner .
  tags:
    - scse-mantid-demo