python2.7:
  variables:
    CI_DEBUG_TRACE: "true"
  script:
    - module load mantid/ORNL_SANS_py2.7
    - virtualenv -p $(which python3) testenv2.7
    - source testenv/bin/activate
    - pip install -r requirements_test.txt
    - pytest -v
python3.6:
  variables:
    CI_DEBUG_TRACE: "true"
  script:
    - module load mantid/ORNL_SANS_py3.6
    - virtualenv -p $(which python3) testenv3.6
    - source testenv/bin/activate
    - pip install -r requirements_test.txt
    - pytest -v
flake8:
  variables:
    CI_DEBUG_TRACE: "true"
  script:
    - flake8
