test:
  variables:
    CI_DEBUG_TRACE: "true"
  script:
    - module load mantid/ORNL_SANS
    - virtualenv -p $(which python2) testenv
    - source testenv/bin/activate
    - pip install -r requirements_test.txt
    - pytest -s -v tests
