stages:
  - dockerbuild

dockerbuild:
  stage: dockerbuild
  script:
    - docker build -t code.ornl.gov:4567/sns-hfir-scse/sans/sans-backend/$CI_COMMIT_REF_NAME:latest .
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push code.ornl.gov:4567/sns-hfir-scse/sans/sans-backend/$CI_COMMIT_REF_NAME:latest
  tags:
    - scse-mantid-builder
  only:
    - c1u-dockerfile
