variables:
  CONTAINER_URL: "code.ornl.gov:4567/sns-hfir-scse/sans/sans-backend/$CI_COMMIT_REF_NAME"
  TEST_SCOPE: "unit"

stages:
  - flake8
  - dockerbuild
  - docker-test
  - code-test
  - script-host

flake8:
  stage: flake8
  allow_failure: true
  script:
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker run -v $PWD:/opt/sans-backend -t code.ornl.gov:4567/sns-hfir-scse/docker-containers/mantid-framework-nightly/master bash -c "flake8 /opt/sans-backend"
  tags:
    - scse-mantid-builder
  only:
    - c1u-dockerfile

dockerbuild:
  stage: dockerbuild
  before_script:
    - docker system prune -f
    - docker image prune -af
  script:
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull code.ornl.gov:4567/sns-hfir-scse/docker-containers/mantid-framework-nightly/master
    - docker build -t $CONTAINER_URL .
    - docker push $CONTAINER_URL
    - sed -i "s|CONTAINER_URL|$CONTAINER_URL|" scripts/sans-backend-run.sh
  tags:
    - scse-mantid-builder
  artifacts:
    paths:
    - scripts/sans-backend-run.sh
  only:
    - c1u-dockerfile

code-unit-test:
  stage: code-test
  dependencies: 
    - dockerbuild
  allow_failure: true
  script:
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_URL
    - docker run -v $PWD:/opt/sans-backend -t $CONTAINER_URL bash -c "conda init bash && bash test_job.sh ${TEST_SCOPE}"
  tags:
    - scse-mantid-builder
  only:
    - c1u-dockerfile

code-integration-test:
  stage: code-test
  dependencies: 
    - dockerbuild
  allow_failure: true
  script:
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_URL
    - docker run -v $PWD:/opt/sans-backend -t $CONTAINER_URL bash -c "conda init bash && bash test_job.sh integration"
  tags:
    - scse-mantid-builder
  only:
    - c1u-dockerfile

docker-update-test:
  stage: docker-test
  dependencies: 
    - dockerbuild
  script:
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_URL
    - sh -x scripts/sans-backend-run.sh -u -- scripts/test.py
  tags:
    - scse-mantid-builder
  only:
    - c1u-dockerfile

docker-no-update-test:
  stage: docker-test
  dependencies: 
    - dockerbuild
  script:
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_URL
    - sh -x scripts/sans-backend-run.sh -- scripts/test.py
  tags:
    - scse-mantid-builder
  only:
    - c1u-dockerfile

script-host:
  stage: script-host
  dependencies: 
    - dockerbuild
  before_script:
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
  script:
    - docker network create nginx || true
    - /usr/local/bin/docker-compose config
    - /usr/local/bin/docker-compose down 
    - /usr/local/bin/docker-compose up --build --force-recreate -d
    - mkdir -p /opt/mantid/sans-backend/$CI_COMMIT_REF_NAME
    - cp -f scripts/sans-backend-run.sh /opt/mantid/sans-backend/$CI_COMMIT_REF_NAME/
  tags:
    - scse-mantid-demo
  only:
    - c1u-dockerfile
