ignore:
  - package:
      name: python
      version: "3.12.*"
    reason: "version pinned by Mantid 6.15.*"

  - package:
      name: gstreamer
      version: "1.26.11"
      type: conda
    reason: "version pinned by Mantid 6.15.*"

  - package:
      name: pyo3
      version: "0.28.3"
      type: rust-crate
    reason: "version pinned by Mantid 6.15.*"
