version: "3.7"
services:
  httpd:
    container_name: httpd
    image: httpd
    ports:
      - "80:80"
    networks:
     - nginx
    volumes:
    - type: bind
      source: /opt/mantid/sans-backend
      target: /usr/local/apache2/htdocs
networks:
 nginx:
  external: true