name: drtsans-dev
channels:
  - mantid/label/main
  - conda-forge
  - defaults
dependencies:
  - mantid=6.8
  - anaconda-client
  - black
  - libmambapy=1.4.2  # auto-selected libarchive=3.6.2 depends on this version
  - boa
  - build
  - conda-build
  - conda-verify
  - docutils
  - graphviz
  - ipywidgets
  - jinja2
  - jsonschema>=3.0.2
  - lmfit
  - mpld3
  - numexpr
  - pandas
  - pip
  - pre-commit
  - pytest >= 3.2
  - pytest-runner
  - pytest-xdist
  - setuptools >= 42
  - sortedcontainers
  - sphinx >= 5.0.2
  - sphinxcontrib-napoleon
  - sphinx_rtd_theme
  - tinydb
  - toml
  - versioningit
  - pip:
      - check-wheel-contents
