name: drtsans-dev
channels:
  - mantid/label/main
  - conda-forge
  - defaults
dependencies:
  # base
  - pip
  - setuptools >= 42
  # packaging
  - anaconda-client
  - boa
  - build
  - conda-build
  - conda-verify
  - versioningit
  # runtime
  - mantid>=6.11
  - numexpr
  - pandas
  - lmfit<1.2.0
  - jinja2
  - graphviz
  - jsonschema>=3.0.2
  - mpld3
  - tinydb
  - toml
  # plot
  # jupyter
  - ipywidgets
  # testing
  - pytest >= 3.2
  - pytest-cov
  - pytest-runner
  - pytest-xdist
  # documentation
  - sphinx >= 5.0.2
  - sphinxcontrib-napoleon
  - sphinx_rtd_theme
  # utliities
  - black
  - libmambapy=1.4.2  # auto-selected libarchive=3.6.2 depends on this version
  - docutils
  - git-lfs
  - pre-commit
  - sortedcontainers
  - pip:
      - check-wheel-contents
