name: drtsans-dev
channels:
  - mantid/label/main
  - conda-forge
  - defaults
dependencies:
  # base
  - pip
  - setuptools >= 42
  # packaging
  - anaconda-client
  - boa
  - conda-build
  - conda-verify
  - python-build
  - versioningit
  # runtime
  - mantid==6.12
  - numexpr
  - pandas
  - lmfit==1.3.3
  - jinja2
  - graphviz
  - jsonschema>=3.0.2
  - mpld3
  - tinydb
  - toml
  # plot
  # jupyter
  - ipywidgets
  # testing
  - pytest >= 3.2
  - pytest-cov
  - pytest-runner
  - pytest-xdist
  # documentation
  - sphinx >= 5.0.2
  - sphinxcontrib-napoleon
  - sphinx_rtd_theme
  # utliities
  - black
  - libmambapy
  - docutils
  - git-lfs
  - pre-commit
  - sortedcontainers
  - pip:
      - check-wheel-contents
