import pytest

from drtsans.tof.eqsans import load_all_files, reduction_parameters, reduce_single_configuration


@pytest.mark.datarepo
def test_reduction_config():
    reduction_input = {
        "background": {"runNumber": None, "transmission": {"runNumber": None, "value": None}},
        "beamCenter": {
            "fallbackBeamCenter": [0.025239, 0.0170801],
            "runNumber": "188546",
            "useFallbackBeamCenter": True,
        },
        "configuration": {
            "1DQbinType": "scalar",
            "AnnularAngleBin": 5.0,
            "LogQBinsPerDecade": None,
            "QbinType": "log",
            "Qmax": None,
            "Qmin": None,
            "StandardAbsoluteScale": 4.9261419618,
            "WedgeMaxAngles": [30.0, 120.0],
            "WedgeMinAngles": [-30.0, 60.0],
            "absoluteScaleMethod": "standard",
            "autoSymmetricWedges": False,
            "autoWedgeAzimuthalDelta": 1.0,
            "autoWedgeBackgroundWidth": 1.5,
            "autoWedgePeakWidth": 0.25,
            "autoWedgePhiMax": 360.0,
            "autoWedgePhiMin": 0.0,
            "autoWedgeQdelta": 0.01,
            "autoWedgeQmax": 0.04,
            "autoWedgeQmin": 0.003,
            "autoWedgeSignalToNoiseMin": 2.0,
            "beamFluxFileName": "/SNS/EQSANS/shared/instrument_configuration/bl6_flux_at_sample",
            "blockedBeamRunNumber": None,
            "cutTOFmax": 2000.0,
            "cutTOFmin": 500.0,
            "darkFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2021A_mp/EQSANS_120577.nxs.h5",
            "defaultMask": None,
            "detectorOffset": 80.0,
            "elasticReference": {
                "runNumber": None,
                "thickness": "1.0",
                "transmission": {"runNumber": None, "value": 0.9},
            },
            "elasticReferenceBkgd": {
                "runNumber": None,
                "transmission": {"runNumber": None, "value": 0.9},
            },
            "fitInelasticIncoh": False,
            "fluxMonitorRatioFile": None,
            "incohfit_factor": None,
            "incohfit_intensityweighted": False,
            "incohfit_qmax": None,
            "incohfit_qmin": None,
            "instrumentConfigurationDir": "/SNS/EQSANS/shared/instrument_configuration",
            "logSliceInterval": 10.0,
            "logSliceName": None,
            "maskFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2021A_mp/mask_4m_general.nxs",
            "mmRadiusForTransmission": 25.0,
            "normalization": "Total charge",
            "numQBins": 60,
            "numQxQyBins": 80,
            "outputWavelengthDependentProfile": False,
            "removeAlgorithmHistory": False,
            "sampleApertureSize": 10.0,
            "sampleOffset": 314.5,
            "scaleComponents": {"detector1": None, "midrange_detector": None, "wing_detector": None},
            "selectMinIncoh": True,
            "sensitivityFileName": (
                "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2025A_mp/Sensitivity_patched_thinPMMA_2o5m_158599.nxs"
            ),
            "smearingPixelSizeX": 0.011,
            "smearingPixelSizeY": 0.007,
            "sourceApertureDiameter": None,
            "subpixelsX": None,
            "subpixelsY": None,
            "timeSliceInterval": 300.0,
            "timeSliceOffset": 0.0,
            "timeSlicePeriod": None,
            "useDefaultMask": True,
            "useDetectorOffset": True,
            "useErrorWeighting": False,
            "useLogQBinsDecadeCenter": False,
            "useLogQBinsEvenDecade": False,
            "useLogSlice": False,
            "useMaskBackTubes": False,
            "usePixelCalibration": False,
            "useSliceIDxAsSuffix": False,
            "useSolidAngleCorrection": True,
            "useSubpixels": False,
            "useThetaDepTransCorrection": True,
            "useTimeSlice": False,
            "wavelengthStep": 0.1,
            "wavelengthStepType": "constant Delta lambda",
        },
        "dataDirectories": None,
        "emptyTransmission": {"runNumber": None, "value": None},
        "instrumentName": "EQSANS",
        "iptsNumber": "37596",
        "outputFileName": "EQSANS_188546",
        "sample": {
            "loadOptions": {},
            "runNumber": "188546",
            "thickness": 1,
            "transmission": {"runNumber": None, "value": None},
        },
        "schemaStamp": "2021-05-12T19:32:03.250291",
    }
    reduction_input.setdefault("configuration", {})
    reduction_input["configuration"]["outputDir"] = "/tmp/reduction_config_test"
    reduction_input = reduction_parameters(parameters_particular=reduction_input, validate=True)

    loaded = load_all_files(reduction_input)
    reduce_single_configuration(loaded, reduction_input)
