FROM code.ornl.gov:4567/rse/images/miniconda3:22.11.1-20230209.1219

# This environment name matches the one in environment.yml
ARG CONDA_ENV=drtsans-dev

COPY environment.yml /tmp/drtsans-dev.yml

# update packages
RUN apt-get update \
    && apt-get upgrade -y \
    # libgl1 and libtiff are needed by mantid
    && apt-get install -y libglu1 libtiff5 make \
    # for data repository as submodule
    && apt-get install -y git-lfs \
    && apt-get autoremove -y \
    && apt-get clean -y

# -- use mamba for faster install
RUN conda env create -n $CONDA_ENV --solver=libmamba -f /tmp/drtsans-dev.yml
RUN conda init -q --all
RUN echo "conda activate $CONDA_ENV" >> ~/.bashrc
