FROM code.ornl.gov:4567/rse/images/miniconda3:22.11.1-20230209.1219

# This environment name matches the one in drtsans-dev.yml
ARG CONDA_ENV=drtsans-dev

COPY drtsans-dev.yml /tmp/drtsans-dev.yml

# update packages
RUN apt-get update \
    && apt-get upgrade -y \
    # libgl1 is needed by mantidworkbench
    && apt-get install -y libglu1 make \
    # for mounting SNS data file (equivalent to previous yum install nfs-utils)
    && apt-get install -y nfs-common nfs-kernel-server \
    && apt-get autoremove -y \
    && apt-get clean -y

# -- use mamba for faster install
RUN conda env create -n $CONDA_ENV --solver=libmamba -f /tmp/drtsans-dev.yml
RUN conda init -q --all
RUN echo "conda activate $CONDA_ENV" >> ~/.bashrc
