# load information from pyproject.toml
{% set pyproject = load_file_data('pyproject.toml') %}
{% set license = pyproject.get('license') %}
{% set description = pyproject.get('description') %}
{% set url = pyproject.get('url') %}
# this will get the version set by environment variable
{% set version = environ.get('VERSION') %}
{% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}

package:
  name: "drtsans"
  version: {{ version }}

source:
  path: ..
#  git_rev: v0.1
#  git_url: git@code.ornl.gov:sns-hfir-scse/sans/sans-backend.git
#  git_url: https://code.ornl.gov/sns-hfir-scse/sans/sans-backend.git

build:
  noarch: python
  number: {{ version_number }}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - versioningit
    - setuptools>=42
    - wheel
  build:
    - python
    - setuptools>=42
    - mantid
    - versioningit

  run:
    - docutils
    - ipywidgets
    - jsonschema>=3.0.2
    - lmfit==1.3.3
    - mantid==6.12
    - mpld3
    - numexpr
    - pandas
    - python {{ python }}
    - sortedcontainers
    - tinydb  # not imported

test:
  imports:
    - mantid
    - drtsans

about:
  home: {{ url }}
  license: {{ license }}
  license_family: APACHE
  license_file: ../LICENSE
  summary: {{ description }}
