# this will reproduce the version from tags to match versioningit
{% set version = environ.get('VERSION', '0.0.0') %}
{% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}

package:
  name: "drtsans"
  version: {{ version }}

source:
  path: ..
#  git_rev: v0.1
#  git_url: git@code.ornl.gov:sns-hfir-scse/sans/sans-backend.git
#  git_url: https://code.ornl.gov/sns-hfir-scse/sans/sans-backend.git

build:
  noarch: python
  number: {{ version_number }}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python=3.8

  build:
    - python=3.8
    - setuptools
    - versioneer
    - mantid

  run:
    - jsonschema>=3.0.2
    - lmfit
    - mpld3
    - numexpr
    - pandas
    - sortedcontainers
    - tinydb  # not imported
    - ipywidgets # not imported
    - python=3.8
    - mantid

test:
  imports:
    - drtsans

about:
  home: https://drtsans.readthedocs.io/
  license: GPL (version 3)
  license_family: GPL3
  license_file: ../LICENSE
