name: Test Suite

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ["v*"]

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.2

      - name: Generate cache key for submodule
        id: generate-cache-key
        run: |
          # Get the submodule commit SHA
          SUBMODULE_SHA=$(git submodule status | awk '{print $1}' | sha256sum | cut -d ' ' -f 1)
          echo "SUBMODULE_KEY=$SUBMODULE_SHA" >> $GITHUB_ENV

      - name: Restore/save LFS files in cache
        id: cache-lfs
        uses: actions/cache@v4
        with:
          path: test/data/drtsans-data/
          key: submodule-${{ env.SUBMODULE_KEY }}

      - name: Pull LFS files for the submodule
        if: steps.cache-lfs.outputs.cache-hit != 'true'
        run: |
          git submodule update --init
          git lfs pull

      - name: Unit test with code coverage
        run: pixi run test -m "not mount_eqsans" -vv --cov=src --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }} # required

  package:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.2

      - name: Build Conda package
        run: pixi run conda-build

      - name: upload conda package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-conda-package
          path: drtsans-*.conda

  conda-verify:
    needs: tests
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test
          init-shell: bash
          create-args: >-
            python=3.10

      - name: Download conda package artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-conda-package
          path: /tmp/local-channel/linux-64

      - name: Install the package
        run: |
          micromamba install --yes -c conda-forge conda-build conda-index
          python -m conda_index /tmp/local-channel
          micromamba install --yes -c /tmp/local-channel -c mantid-ornl -c conda-forge drtsans

      - name: Verify the installation
        run: python -c "import drtsans"
