name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ['v*']

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge,defaults
          use-mamba: true
          environment-file: environment.yml
          lfs: true
          submodules: recursive
      - name: install additional dependencies
        run: |
          echo "installing additional dependencies if cannot be installed from conda"
      - name: test preparation
        run: |
          versioningit -vw
          mkdir .coverage.d
          mkdir .results.d
          git lfs pull
          git submodule update --init --recursive
      - name: run unit tests
        run: |
          echo "running unit tests"
          python -m pytest -m "not mount_eqsans" -vv --dist loadscope -n 2 --cov=src --cov-report=xml:.coverage.d/unit.xml --cov-report=term --junitxml=./.results.d/unit.xml tests/unit/
      - name: run integration tests
        run: |
          echo "running integration tests"
          python -m pytest -m "not mount_eqsans" -vv --dist loadscope -n 2 --cov=src --cov-report=xml:.coverage.d/integration.xml --cov-report=term --junitxml=./.results.d/integration.xml tests/integration/
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v5
        if:
          github.actor != 'dependabot[bot]'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .coverage.d/
      - name: build conda package
        run: |
          # test that the conda package builds
          cd conda.recipe
          echo "versioningit $(versioningit ../)"
          # conda channels could have been defined in the conda-incubator, but you can copy/paste the lines
          # below to build the conda package in your local machine
          CHANNELS="--channel mantid/label/main --channel conda-forge"
          VERSION=$(versioningit ../) conda mambabuild $CHANNELS --output-folder . .
          conda verify noarch/drtsans*.tar.bz2
